version: '3'
services:
  # firebase cli
  firebase:
    build: ./firebase
    # firebaseのトークンは環境変数で管理。セキュリティのためgit管理しない。
    env_file: .env
    volumes:
      - ../app/public:/app/public
      - ./config/firebase/.firebaserc:/app/.firebaserc
      - ./config/firebase/firebase.json:/app/firebase.json
    ports:
      - 5000:5000
      - 9005:9005
    command: [firebase, serve, -p, "5000", -o, "0.0.0.0", --token, "$FIREBASE_TOKEN"]

  # cssプリプロセッサ
  precss:
    build: ./precss
    volumes:
      - ./precss/app.js:/app/app.js
      - ../htdocs/css:/app/src
      - ../app/public/assets/css:/app/dest
    command: [npm, run, run]

# htmlテンプレートエンジン
  pug:
    build: ./pug
    volumes:
      - ../htdocs/pug:/app/src
      - ../app/public:/app/dist
    environment:
      - SHELL=/bin/bash
    command: [npm, run, watch]

  # エクセル取込
  excel:
    build: ./excel
    volumes:
      - ./excel/app.js:/app/app.js
      - ../data:/app/data
      # pugの変数定義ファイルに書き出し
      - ../htdocs/pug/includes/common:/app/dest
  
  # ソースコードプロトタイピング
  s2s:
    build: ./s2s
    volumes:
      - ../htdocs/scripts/characterSheets:/app/src
      - ./config/s2s/s2s.config.js:/app/s2s.config.js
      - ./config/s2s/templates:/app/templates